name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' # May need to allow prerelease version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish PackageReferenceCleaner/PackageReferenceCleaner.csproj -c Release --nologo

    - name: Change base-tag in index.html for GitHub Pages
      run: sed -i 's|<base href="/" />|<base href="/PackageReferenceCleaner/" />|g' PackageReferenceCleaner/bin/Release/net10.0/publish/wwwroot/index.html

    - name: Copy index.html to 404.html (for client-side routing)
      run: cp PackageReferenceCleaner/bin/Release/net10.0/publish/wwwroot/index.html PackageReferenceCleaner/bin/Release/net10.0/publish/wwwroot/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: PackageReferenceCleaner/bin/Release/net10.0/publish/wwwroot